---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: bubba/archlinux:aarch64
    pull: false
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
