---

 - import_tasks: install_packages.yml
   tags:
    - aur
    - master_node
    - k3s
   when: ansible_os_family == "Archlinux"

 - import_tasks: master_service_setup.yml
   tags:
    - master_node
    - k3s
   host: k3s_master

 - import_tasks: master.yml
   tags:
    - master_node
    - k3s
   host: k3s_master
