---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: 'k3s.master.service.j2'
    dest: '{{ systemd_dir }}/k3s.service'
    owner: root
    group: root
    mode: 0755
  notify: k3s_service_restart

- name: Start the k3s_service
  meta: flush_handlers
