- name: Stat YaY
  stat:
    path: /usr/bin/yay
  register: yay_result

- name: Create User
  user:
    name: '{{ user }}'
    create_home: yes
    system: yes
    group: wheel
  when:
    yay_result.stat.exists == False

- name: Add AUR Build User to Sudoers
  lineinfile:
    path: '/etc/sudoers.d/{{ user }}_sudo'
    line: '{{ user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
  when:
    yay_result.stat.exists == False

- name: Install AUR Utils
  become: yes
  become_user: bubba
  aur:
    use: makepkg
    state: present
    name:
      - aurcle
      - yay
  when:
    yay_result.stat.exists == False

- name: Install k3s
  become: yes
  become_user: aur_builder
  aur:
    use: yay
    state: present
    name:
      - k3s-bin

- name: Install Docker
  pacman:
    state: present
    name:
      - docker
      - containerd
      - runc
