---
# tasks file for users
- include_tasks: users.yml
  tags: users

- include_tasks: time_zone.yml
  tags: time_zone

- include_tasks: packages.yml
  tags: base_packages
  when: ansible_os_family == "Archlinux"

- include_tasks: overcloc_pis.yml
  tags: overclock



