---
# tasks file for users
- import_tasks: time_zone.yml
  tags:
    - time_zone
    - first_run

- import_tasks: packages.yml
  tags:
    - base_packages
    - first_run
  when: ansible_os_family == "Archlinux"

- import_tasks: users.yml
  tags:
    - users
    - first_run

- import_tasks: remove_users.yml
  tags:
    - users

- import_tasks: overclock_pis.yml
  tags:
    - overclock

