---
# tasks file for users
- import_tasks: time_zone.yml
  tags:
    - time_zone
    - first_run

- import_tasks: hostname.yml
  tags:
    - hostname
    - first_run

- import_tasks: packages.yml
  tags:
    - base_packages
    - first_run
    - update
  when: ansible_os_family == "Archlinux"

- import_tasks: install_yay.yml
  tags:
    - yay
  when: ansible_os_family == "Archlinux"

- import_tasks: users.yml
  tags:
    - users
    - first_run

- import_tasks: remove_users.yml
  tags:
    - users

- import_tasks: overclock_pis.yml
  tags:
    - overclock

- import_tasks: c_groups.yml
  tags:
    - c_groups

- import_tasks: migrate_kernels.yml
  tags:
    - kernels
    - kernel
