---
- name: Install Wanted RPI Kernel
  pacman:
    state: present
    force: yes
    name:
      - linux-raspberrypi4
      - linux-raspberrypi4-headers
  notify: reboot

- name: Point boot to mmcblk0p0
  lineinfile:
    path: /etc/fstab
    regex: '^/dev/mmcblk1p1*'
    line: '/dev/mmcblk0p1   /boot   vfat    defaults    0   0'
