
- name: Overvolt RasPi
  lineinfile:
    path: /boot/config.txt
    regexp: '^over_voltage=6'
    line: over_voltage=6
  notify: reboot

- name: Overclock RasPi CPU
  lineinfile:
    path: /boot/config.txt
    regexp: '^arm_freq=2000'
    line: arm_freq=2000
  notify: reboot

- name: Underclock RasPi GPU
  lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_freq=400'
    line: gpu_freq=400
  notify: reboot
  when:
    - inventory_hostname in groups['k3s_cluster']

- name: Use Less GPU Memory
  lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_mem=16'
    line: gpu_mem=16
  notify: reboot
  when:
    - inventory_hostname in groups['k3s_cluster']

- name: Overclock RasPi GPU
  lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_freq=*'
    line: gpu_freq=750
  notify: reboot
  when:
    - inventory_hostname in groups['desk']

- name: Use More GPU Memory
  lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_mem=*'
    line: gpu_mem=256
  notify: reboot
  when:
    - inventory_hostname in groups['desk']
