
- name: Update Package Cache and Packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install Wanted Packages
  pacman:
    state: present
    name:
      - neovim
      - htop
      - wget
      - rsync
      - grml-zsh-config
