
- name: Create User
  user:
    name: "{{ user }}"
    create_home: yes
    system: yes
    group: wheel
    shell: /bin/zsh
    password: "{{ user_pass }}"

- name: Grant User Sudo Privs
  lineinfile:
    path: '/etc/sudoers.d/{{ user }}_sudo'
    line: '{{ user }} ALL=(ALL) ALL'
    create: yes

- name: Create .ssh Dir
  file:
    path: '/home/{{ user }}/.ssh'
    state: directory
    owner: bubba
    mode: 0775

- name: Create authorized_keys File
  file:
    path: '/home/{{ user }}/.ssh/authorized_keys'
    owner: bubba
    mode: 0600

- name: Grant SSH Access
  lineinfile:
    path: /home/bubba/.ssh/authorized_keys
    regexp: '^ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDP939dC/*'
    line: '{{ public_ssh_key }}'

- name: Set Root Password
  user:
    name: root
    password: '{{ user_pass }}'

