---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_centos_common
    image: centos:8
  - name: instance_arch_common
    image: bubba/archlinux:aarch64
    pull: false
provisioner:
  name: ansible
verifier:
  name: ansible
